### ISSUE TITLE
New Site Defaults.

### ISSUE THREAD

**Issue by andysavage** [DirectSponsor/DS5.1#3]
Can we make a default for a new site that already has settings like home page, posts page etc? To save coordinators having to do a lot of setting up? - [This page](http://wordpress.stackexchange.com/questions/12204/multisite-setting-theme-and-options-when-a-new-blog-is-created) may have some useful pointers. I found a plug-in, [here](https://wordpress.org/plugins/wpmu-new-blog-defaults/) but it's not maintained.

**Comment by andysavage** [comment]
This was from when we were using WPMU, now they are separate sites so I will close this. If the theme and accounts plug-in are available freely then any new project will get the theme anyway so the defaults will be in that. 

Is that right or will we need to put anything else in the repo?

**Comment by wasilzafar** [comment]
I agree with that - new project will get the theme and subsequently defaults. It's OK to close.
